[site]
DefaultTitle  = "JKHao"
DefaultLayout = "shared/layout.html"
DefaultError  = "shared/error.html"

SessionCoolieName = "mycookiesessionnameid"
SessionExpires    = 1 # session保持时间 /小时

#调试开关
APPDebug     = true #IRIS框架调试模式 true
DblogerModel = true #Gorm调试模式

AdminId = 1 #系统管理 不允许删除

UploadSize         = 5               #允许上传文件的大小 单位M
UploadSuffixExists = ".jpg,.png,.jpge,.gif" #允许上传文件的后缀

[server]
# domain = "127.0.0.1"
domain = "192.168.114.128"
port   = "8080"

[pagination]
PageSize = 10

FrontendPageSize = 5 #前端

[redis]

Network = "tcp"
Addr = "127.0.0.1:6379"
Password = ""
Database = ""
#IdleTimeout service.DefaultRedisIdleTimeout,
refix=     ""
Host = "127.0.0.1:6379"
MaxIdle = 30
MaxActive = 30
IdleTimeout = 200

